export const DEFAULT_RESTART_HEALTH_TIMEOUT_MS = 60_000;

export const DEFAULT_RESTART_HEALTH_DELAY_MS = 500;
export const DEFAULT_RESTART_HEALTH_ATTEMPTS = Math.ceil(
  DEFAULT_RESTART_HEALTH_TIMEOUT_MS / DEFAULT_RESTART_HEALTH_DELAY_MS,
);

export const INTERRUPTED_UPDATE_SETTLE_PROBES = Math.ceil(DEFAULT_RESTART_HEALTH_ATTEMPTS / 10);
export const INTERRUPTED_UPDATE_SETTLE_TIMEOUT_MS =
  Math.floor(DEFAULT_RESTART_HEALTH_TIMEOUT_MS / 4) +
  (INTERRUPTED_UPDATE_SETTLE_PROBES - 1) * DEFAULT_RESTART_HEALTH_DELAY_MS;
