export const MEMORY_SEARCH_FIELD_LABELS: Record<string, string> = {
  "memory.search": "Memory Search",
  "memory.search.enabled": "Enable Memory Search",
  "memory.search.rememberAcrossConversations": "Remember Across Conversations",
  "memory.search.sources": "Memory Search Sources",
  "memory.search.extraPaths": "Extra Memory Paths",
  "memory.search.extraPaths.*.path": "Extra Memory Path",
  "memory.search.extraPaths.*.pattern": "Extra Memory Path Pattern",
  "memory.search.extraPaths.*.evergreen": "Evergreen Extra Memory Path",
  "memory.search.multimodal": "Memory Search Multimodal",
  "memory.search.multimodal.enabled": "Enable Memory Search Multimodal",
  "memory.search.multimodal.modalities": "Memory Search Multimodal Modalities",
  "memory.search.multimodal.maxFileBytes": "Memory Search Multimodal Max File Bytes",
  "memory.search.experimental.sessionMemory": "Memory Search Session Index (Experimental)",
  "memory.search.provider": "Memory Search Provider",
  "memory.search.remote.baseUrl": "Remote Embedding Base URL",
  "memory.search.remote.apiKey": "Remote Embedding API Key",
  "memory.search.remote.headers": "Remote Embedding Headers",
  "memory.search.remote.batch.enabled": "Remote Batch Embedding Enabled",
  "memory.search.model": "Memory Search Model",
  "memory.search.inputType": "Memory Search Input Type",
  "memory.search.queryInputType": "Memory Search Query Input Type",
  "memory.search.documentInputType": "Memory Search Document Input Type",
  "memory.search.outputDimensionality": "Memory Search Output Dimensionality",
  "memory.search.fallback": "Memory Search Fallback",
  "memory.search.local.modelPath": "Local Embedding Model Path",
  "memory.search.store.vector.enabled": "Memory Search Vector Index",
  "memory.search.store.vector.extensionPath": "Memory Search Vector Extension Path",
  "memory.search.query.maxResults": "Memory Search Max Results",
  "memory.search.query.minScore": "Memory Search Min Score",
  "memory.search.cache.enabled": "Memory Search Embedding Cache",
};
